### ISSUE TITLE
[FEATURE] Update README

### ISSUE THREAD

**Issue by geoidesic** [arbron/fvtt-compendium-tools#13]
Could you please update the README to be a bit more descriptive?

Specifically:

# Replace Entry
-  Replace compendium entries with a saved item while retaining the item's ID. This will prevent breaking of links between items in the compendium.

Could you explain what `saved item` means? I can think of about six different contexts for this that all mean different things. Also what do you mean by "breaking of links"? It's really not clear to me what this is doing, nor why.

# View Module Manifest
- View Module Manifest: View the complete manifest information for any installed module. Access this information by going to the Manage Modules screen in Game Settings, right clicking on the module you would like to view, and selecting View Manifest.

Could you explain why one might wish to do this?

**Comment by geoidesic** [comment]
Wontfix with no explanation.. amazing :(

**Comment by arbron** [comment]
> Wontfix with no explanation.. amazing :(

The explanation is the module is no longer being developed, so I've closed all open issues.
