### ISSUE TITLE
[BUG] Conflict with Monk's Little Details

### ISSUE THREAD

**Issue by DivertedCircle** [arbron/fvtt-compendium-tools#4]
**Describe the bug**
The Replace Entry option does not appear in the drop down list when right clicking an entry in a compendium when v1.0.16 of Monk's Little Details is enabled. This is likely due to the new feature they've added: 'Added context menu to view scene artwork in a compendium.'
https://github.com/ironmonk88/monks-little-details

**To Reproduce**
1. Enable both modules.
2. Right click a compendium entry.
3. See error

**Expected behavior**
The Replace Entry option should be listed in the menu.

**Environment:**
 - Foundry Core Version: [e.g. 0.7.9]
 - Module Versions: Arbron's Compendium Tools v0.3.1, Monk's Little Details v1.1.16
 - Host: Forge
 - OS & Browser Firefox

**Comment by JJBocanegra** [comment]
[I opened an issue in Monk's Little Details repository](https://github.com/ironmonk88/monks-little-details/issues/32), who is the responsible for the bug, it makes no sense here in my opinion.

**Comment by arbron** [comment]
Fixed in the 0.4.0 release. Thanks for letting me know about it :).
