### ISSUE TITLE
[BUG] Replace Entry doesn't work well.

### ISSUE THREAD

**Issue by Altrix1** [arbron/fvtt-compendium-tools#7]
Replace Entry doesn't work well. Only adds changes (does not remove old elements)

![image](https://user-images.githubusercontent.com/86872105/126864765-fee9ed89-0d98-4ab2-877e-6595712dea62.png)
![image](https://user-images.githubusercontent.com/86872105/126864771-e3d520e3-9582-478e-a35a-dda2ac9b43e4.png)
![image](https://user-images.githubusercontent.com/86872105/126864780-1b88215c-29a8-467c-aacc-43bddf52f39e.png)

**Comment by Shuggaloaf** [comment]
@Altrix1 or @arbron is this still an issue in newer releases? Just trying to determine before installing the mod and I don't see that there's been any response/update on this.

**Comment by Altrix1** [comment]
@Shuggaloaf  Still not working well

**Comment by Shuggaloaf** [comment]
@Altrix1 That's a shame. Thanks for the reply!
